steps:
  # 1) Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-dash-app'
      - '.'

  # 2) Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/my-dash-app'

  # 3) Deploy the image to Cloud Run (fully managed)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-dash-app'
      # Image to deploy
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-dash-app'
      # Region for Cloud Run (e.g., us-central1)
      - '--region'
      - 'us-central1'
      # Allow unauthenticated (so anyone can access your app)
      - '--allow-unauthenticated'
      # Set port to 8080, if needed
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/my-dash-app'

options:
  logging: CLOUD_LOGGING_ONLY
